lr: 0.0002
seed: 3
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 8
val_batch: 8
test_batch: 8
gather_train_batch: 8
gather_val_batch: 8
num_workers: 8
model_name: 'refine-64'
data_filepath: '/data/physics_prediction_v2/data'
dataset: 'single_pendulum'
num_frames: 60
lr_schedule: [20, 50, 100, 300, 600]
lda1: 10.0
lda2: 1.0
lda3: 100.0
beta: 0.0
num_gpus: 1
epochs: 500