lr: 0.0005
seed: 3
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 8
val_batch: 8
test_batch: 8
num_workers: 8
model_name: 'encoder-decoder-64'
data_filepath: '/data/physics_prediction_v2/data'
dataset: 'double_pendulum'
num_frames: 60
lr_schedule: [20, 50, 100, 300, 600]
lda1: 0.01
lda2: 0.1
lda3: 0.0
beta: 0.1
num_gpus: 1
epochs: 2000