lr: 0.0001
seed: 1
if_cuda: True
gamma: 0.5
log_dir: '../logs'
train_batch: 4
val_batch: 4
test_batch: 4
num_workers: 8
model_name: 'encoder-decoder-64'
data_filepath: '/data/physics_prediction_v2/data'
dataset: 'lava_lamp'
num_frames: 60
lr_schedule: [20, 50, 100, 300, 600]
lda1: 0.0
lda2: 1.0
lda3: 0.0
beta: 0.0
num_gpus: 1
epochs: 1000